version: '3.8'
services:
  db:
    image: postgres:15 # 버전을 명시해주는 게 좋습니다
    restart: always
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "elqkfel0608@!@" # 최소 12자 이상 추천
    ports:
      - "127.0.0.1:5432:5432" # 중요! 앞에 127.0.0.1을 붙여야 외부에서 못 들어옵니다.
    volumes:
      - ./postgres_data:/var/lib/postgresql/data